version: '2'
services:
  web-wallet:
    build: ../web-wallet/
    container_name: web-wallet
    restart: always
    user: 1005:1006  # bitspark:bitspark
    volumes:
      - "/mnt:/mnt"
    expose:
      - "8080"
    networks:
      - web
    environment:
      - LNCLI=/mnt/data/lightning/lightning/cli/lightning-cli --lightning-dir=/mnt/data/lightning/data_testnet
      - PORT=8080
      - PGHOST=database

  proxy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    networks:
      - web

  database:
    container_name: database
    restart: always
    image: postgres:latest
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql
    networks:
      - web
    ports:
      - "5432:5432"

volumes:
  database-volume:

networks:
  web:
