version: '2.1'

x-logging:
  &default-logging
  driver: syslog
  options:
    syslog-address: "tcp://splunk:1234"
    tag: "{{.Name}}/{{.ID}}"

services:
  web-wallet:
    build: ../web-wallet/
    container_name: web-wallet
    restart: always
    user: 1005:1006  # bitspark:bitspark
    logging: *default-logging
    networks:
      - web
    environment:
      - HTTP_LOG_FORMAT=tiny
      - WALLET_LND_REST_URL=https://bit-1.biluminate.net:29735
      - WALLET_LND_REST_MACAROON=${WALLET_LND_REST_MACAROON}
      - PORT=8080
      - PGHOST=database

  backend:
    build: ../backend/
    container_name: backend
    restart: always
    expose:
      - "4000" # wallet API
      - "5000" # pay WEB
    networks:
      - web
    logging: *default-logging
    environment:
      - WALLET_PORT=4000
      - WALLET_LND_REST_URL=https://bit-1.biluminate.net:29735
      - WALLET_LND_REST_MACAROON=${WALLET_LND_REST_MACAROON}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PGHOST=database
      - PGDATABASE=wallet_api_prod
      - PAY_PORT=5000
      - CANTEEN_LND_REST_URL=https://bit-1.biluminate.net:29736
      - CANTEEN_LND_REST_MACAROON=${CANTEEN_LND_REST_MACAROON}

  proxy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    networks:
      - web
    logging: *default-logging
    environment:
      - ACME_AGREE=true

  database:
    container_name: database
    image: postgres:10.3
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql
    networks:
      - web
    logging: *default-logging

  splunk:
    container_name: splunk
    image: splunk/splunk
    restart: always
    volumes:
      - splunk-etc-volume:/opt/splunk/etc
      - splunk-var-volume:/opt/splunk/var
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_USER=root

volumes:
  database-volume:
  splunk-etc-volume:
  splunk-var-volume:

networks:
  web:
