version: '2'
services:
  web-wallet:
    build: ../web-wallet/
    container_name: web-wallet
    restart: always
    user: 1005:1006  # bitspark:bitspark
    networks:
      - web
    environment:
      - HTTP_LOG_FORMAT=tiny
      - WALLET_LND_REST_URL=https://bit-1.biluminate.net:29735
      - WALLET_LND_REST_MACAROON=${WALLET_LND_REST_MACAROON}
      - PORT=8080
      - PGHOST=database

  backend:
    build: ../backend/
    container_name: backend
    restart: always
    expose:
      - "4000" # wallet API
      - "5000" # pay WEB
    networks:
      - web
    environment:
      - WALLET_PORT=4000
      - WALLET_LND_REST_URL=https://bit-1.biluminate.net:29735
      - WALLET_LND_REST_MACAROON=${WALLET_LND_REST_MACAROON}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PGHOST=database
      - PGDATABASE=wallet_api_prod
      - PAY_PORT=5000
      - CANTEEN_LND_REST_URL=https://bit-1.biluminate.net:19735
      - CANTEEN_LND_REST_MACAROON=${CANTEEN_LND_REST_MACAROON}

  proxy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    networks:
      - web
    environment:
      - ACME_AGREE=true

  database:
    container_name: database
    restart: always
    image: postgres:10.3
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql
    networks:
      - web

volumes:
  database-volume:

networks:
  web:
