version: '2'
services:
  web-wallet:
    build: ../web-wallet/
    container_name: web-wallet
    restart: always
    user: 1005:1006  # bitspark:bitspark
    volumes:
      - "../web-wallet:/app"
      - "/mnt:/mnt"
    expose:
      - "8080"
    networks:
      - web
    environment:
      - LNCLI=/mnt/data/lightning/lightning/cli/lightning-cli --lightning-dir=/mnt/data/lightning/data_testnet
      - PORT=8080
  proxy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    networks:
      - web

networks:
  web:
