version: '2'
services:
  web-wallet:
    image: node:8
    container_name: web-wallet
    restart: always
    user: 1005:1006  # bitspark:bitspark
    volumes:
      - "../web-wallet:/app"
      - "/mnt:/mnt"
    expose:
      - "80"
    networks:
      - web
    command: make LNCLI='/mnt/data/lightning/lightning/cli/lightning-cli --lightning-dir=/mnt/data/lightning/data_testnet' PORT=80 -C /app run
  proxy:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    networks:
      - web

networks:
  web:
