#!/bin/bash

handle_invoice() {
    cat <<EOF
{
    "payment_hash" : "a3fe33c774c2c9e98fd5a8fbcdebc8eeb6adbeb7d9e2ae8314aeee39f7fa004a",
    "expiry_time" : 1519142510,
    "expires_at" : 1519142510,
    "bolt11" : "lntb500u1pdgcwz7pp550lr83m5cty7nr744raum67ga6m2m04hm832aqc54mhrnal6qp9qdqgt96k6mtecqpxgsn30trds4g8ywdruw6uz0yfv27ltj0hh36f3hr7v3y2z5jfdj84jsxmtsmvx90dej59rx9xsyd3qylfvhss49v7h5gtaf8695zvu6sqnmcxkf"
}
EOF
}

COMMAND="$1"

case "$COMMAND" in
    invoice)
        handle_invoice
        ;;
    *)
        echo Unknown command
        ;;
esac
