version: '2.1'

x-logging:
  &default-logging
  driver: syslog
  options:
    syslog-address: "tcp+tls://logs2.papertrailapp.com:29083"
    tag: "{{.Name}}/{{.ID}}"

services:
  web-wallet:
    build: ../web-wallet/
    restart: always
    user: 1005:1006  # bitspark:bitspark
    logging: *default-logging
    networks:
      - web
    environment:
      - HTTP_LOG_FORMAT=tiny
      - WALLET_LND_REST_URL=${WALLET_LND_REST_URL}
      - WALLET_LND_REST_MACAROON=${WALLET_LND_REST_MACAROON}
      - PORT=8080
      - PGHOST=database

  backend:
    build:
      context: ../backend/
      args:
        - FAKE_LND_ENABLED=${FAKE_LND_ENABLED}
    restart: always
    expose:
      - "4000" # wallet API
      - "5000" # pay WEB
    networks:
      - web
    logging: *default-logging
    environment:
      - WALLET_PORT=4000
      - WALLET_LND_REST_URL=${WALLET_LND_REST_URL}
      - WALLET_LND_REST_MACAROON=${WALLET_LND_REST_MACAROON}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PGHOST=database
      - PGDATABASE=wallet_prod
      - PAY_PORT=5000
      - PAY_WALLET_URL=${PAY_WALLET_URL:-https://testwallet.biluminate.com}
      - CANTEEN_LND_REST_URL=${CANTEEN_LND_REST_URL}
      - CANTEEN_LND_REST_MACAROON=${CANTEEN_LND_REST_MACAROON}

  proxy:
    image: abiosoft/caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    networks:
      - web
    logging: *default-logging
    environment:
      - ACME_AGREE=true

  database:
    image: postgres:10.3
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql
    networks:
      - web
    logging: *default-logging

volumes:
  database-volume:

networks:
  web:
