version: '2.1'

services:
  web-wallet:
    build: ../web-wallet/
    restart: always
    user: 1005:1006  # bitspark:bitspark
    networks:
      - web
    environment:
      - HTTP_LOG_FORMAT=tiny
      - PORT=8080

  backend:
    build:
      context: ../backend/
      args:
        - FAKE_LND_ENABLED=${FAKE_LND_ENABLED}
    restart: always
    expose:
      - "4000" # wallet API
      - "5000" # pay WEB
    networks:
      - web
    environment:
      - WALLET_PORT=4000
      - WALLET_LND_REST_URL=${WALLET_LND_REST_URL}
      - WALLET_LND_REST_MACAROON=${WALLET_LND_REST_MACAROON}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PGHOST=database
      - PGDATABASE=wallet_prod
      - PAY_PORT=5000
      - PAY_WALLET_URL=${PAY_WALLET_URL:-https://testwallet.biluminate.com}
      - CANTEEN_LND_REST_URL=${CANTEEN_LND_REST_URL}
      - CANTEEN_LND_REST_MACAROON=${CANTEEN_LND_REST_MACAROON}
      - WALLET_MAILGUN_API_KEY=${WALLET_MAILGUN_API_KEY}

  proxy:
    image: abiosoft/caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    networks:
      - web
    environment:
      - ACME_AGREE=true
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}

  database:
    image: postgres:10.3
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql
    networks:
      - web

  logspout:
    image: gliderlabs/logspout:v3.2.5
    command: ${LOGS_DST:-syslog://splunk:1514,syslog+tls://logs2.papertrailapp.com:29083}
    networks:
      - web
    environment:
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  splunk:
    image: splunk/splunk
    restart: always
    volumes:
      - splunk-etc-volume:/opt/splunk/etc
      - splunk-var-volume:/opt/splunk/var
    networks:
      - web
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_USER=root

volumes:
  database-volume:
  splunk-etc-volume:
  splunk-var-volume:

networks:
  web:
