version: '2'
services:
  web:
    depends_on:
      - database
    image: node:9
    ports:
      - "8080:8080" # webpack dev server
      - "8081:8081" # api/backend
    volumes:
      - ./:/app
    environment:
      - LND_REST_URL=http://localhost:8081
      - LND_REST_MACAROON=foobaroon
      - PGHOST=database
    command: "make -C /app dev"

  database:
    restart: always
    image: postgres:10.3
    volumes:
      - database-volume:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  database-volume:
